### PR TITLE
#164726566 add serializers to all views

### PR DESCRIPTION
**Pull request by joelethan**
#### What does this PR do?
- This PR fixes the functionality of the core-api

#### Description of Task to be completed?
- Add serializers to social auth views
- Add a serializer to the FavoriteHandlerView

#### How should this be manually tested?
- Clone the repo, cd into `Ah-backend-aquaman` and checkout the branch `origin/bg-fix-serializers-core-api-164726566`
    -  pip install -r requirements.txt
    -  python manage.py makemmigrations
    -  python manage.py migrate
    -  python manage.py runserver
    -  Access `http://127.0.0.1:8000/docs/` to use core-api

#### What are the relevant pivotal tracker stories?
- [#164726566](https://www.pivotaltracker.com/story/show/164726566)

### CODE REVIEW

**Comment by Peace-Apple** [comment]
Thanks for fixing @joelethan

**Comment by Peace-Apple** [comment]
Please rename your branch @joelethan, the current name is quite confusing

**Comment by Peace-Apple** [comment]
Good work @joelethan, locally the documentation now works fine but via Heroku am still getting the other error, trying to figure out what the issue could be

**Review by BagzieGracious — DISMISSED** [review]
Thanks for the good work @joelethan

**Review by CryceTruly — APPROVED** [review]

**Review by BagzieGracious — APPROVED** [review]

**Review by wasibani-roy — APPROVED** [review]

**Pull request merged**
