### PR TITLE
#164069226 Like and or Dislike articles

### PR DESCRIPTION
**Pull request by BagzieGracious**
**What does this PR do**
- This PR enables authenticated user to like or dislike an article.

**Description of Task to be completed?**

- Enable an authenticated user to like or dislike an article
- Calculates the number of dislikes or likes of an article

**How should this be manually tested?**

- Clone the repo and cd into Ah-backend-aquaman
- git checkout `ft-like-articles-164069226`
- pip install -r requirements.txt
- python manage.py makemigrations
- python manage.py migrate
- python manage.py runserver
- Register and then login into the system
- Then navigate to `http://127.0.0.1:8000/api/articles/<slug>/like/`

**Any background context you want to provide?**
- N/A

**What are the relevant pivotal tracker stories?**

- [#164069226](https://www.pivotaltracker.com/story/show/164069226)

**Screenshots**
- example of liking an article

Screenshot 2019-03-13 at 22 55 56

- example of disliking an article

Screenshot 2019-03-13 at 22 56 21

- example of number likes and dislikes

Screenshot 2019-03-13 at 22 58 35

### CODE REVIEW

**Comment by Peace-Apple** [comment]
Good work Deogratius, I have reviewed and all works fine locally, however add a line at the end of the .codeclimate.yml file

**Comment by BagzieGracious** [comment]
> Good work Deogratius, I have reviewed and all works fine locally, however add a line at the end of the .codeclimate.yml file

**Review by Peace-Apple — APPROVED** [review]
Good work, feedback worked on.

**Review by wasibani-roy — APPROVED** [review]
Good work @BagzieGracious looks good

**Review by joelethan — APPROVED** [review]
LGTM

**Review by CryceTruly — APPROVED** [review]
LGTM

**Pull request merged**
